version: '4.23.0'

services:
  postgres_app:
    image: postgres:latest
    container_name: postgres_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: generic
    ports:
      - "5432:5432"
  postgres_keycloak:
    image: postgres:latest
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_srv
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "1521:1521"
      - "8082:8080"
      - "49160:22"
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: minio_srv
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ACCESS_KEY: 'test'
      MINIO_SECRET_KEY: 'test'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: '0.0.0.0:9001'
    command: minio server /data